# mvTCR Preprocessing
mvTCR uses a specific format to handle single-cell data, which is based on AnnData objects. If not otherwise stated, we follow the speficition from Scanpy [1] and Scirpy [2]. However, we need some additional information to utilize all functions of mvTCR. In this notebook, we introduce the mvTCR preprocessing pipeline, which adds the required information to the corresponding place in the AnnData object.

All experiments in our paper where conducted on Datasets:
- after Quality Control (cell filtering, doublet detection, ...)
- with normalized and log+1 transformed count data

The pipeline assumes that these steps have already been performed. For further reference, please see Luecken et al [3].

If you know what you are doing: different normalization, log-stabilizing transformations, etc. can also be used, but need to be handled with care!


[1] Wolf, F. A., Angerer, P. & Theis, F. J. Scanpy: large-scale single-cell gene expression data analysis. Genome biology 19, 1–5 (2018).

[2] Sturm, G. et al. Scirpy: a scanpy extension for analyzing single-cell t-cell receptor-sequencing data. Bioinformatics 36, 4817–4818 (2020).

[3] Luecken, M. D. & Theis, F. J. Current best practices in single-cell rna-seq analysis: a tutorial.
Molecular systems biology 15, e8746 (2019).

## Prerequisits

The preprocessing pipeline is showcased on the dataset from Stephenson et al. [4], which can be readily downloaded from:

- https://covid19.cog.sanger.ac.uk/submissions/release1/haniffa21.processed.h5ad
- https://www.ebi.ac.uk/biostudies/files/E-MTAB-10026/TCR_merged-Updated.tsv

and is already quality-controled. 

[4] Stephenson, E. et al. Single-cell multi-omics analysis of the immune response in covid-19. Nature medicine 27, 904–916 (2021).


The mvTCR preprocessing pipeline is taylored for mvTCR-usage and handles the encoding of clonotypes and conditional variables in the required format. However, it is necessary that the adata object is already log-normalized, subsetted to highly variable genes and contains scirpy-encoded TCR information. We demonstrate these steps below.

In [1]:
import scanpy as sc
import scirpy as ir
import pandas as pd

c:\Users\Jan\.conda\envs\mvtcr_preprocheck\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
path_gex = '../data/Haniffa/haniffa21.processed.h5ad'
path_tcr = '../data/Haniffa/TCR_merged-Updated'

We will load the transcriptome data. To speed up runtime, we will downsample the data to two patients.

In [12]:
adata = sc.read(path_gex)

selected_patients = ['AP1', 'CV0062']
adata = adata[adata.obs['patient_id'].isin(selected_patients)].copy()

Before starting, we take the raw expression counts matrix, total-count normalize it to 10,000 reads per cell to correct for differences in library-size, and logarithmize it:

In [13]:
adata.X = adata.layers['raw']
print(adata.X[0:4,11:20].toarray())
sc.pp.normalize_total(adata, target_sum=1e4)
sc.pp.log1p(adata)
print(adata.X[0:4,11:20].toarray())

[[1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1.1596017 0.        0.        0.        0.        1.1596017 0.
  0.        0.       ]
 [0.        0.        0.        0.        0.        1.52811   0.
  0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.        0.       ]
 [0.        0.        0.        0.        0.        0.        0.
  0.        0.       ]]


To keep the most informative genes, we subset our matrix to the 5000 highest-variable genes. This number can be changed based on the expected variation, and noisy or technical-artifact related genes can be excluded based on prior knowledge.

In [14]:
print('Shape before: ', adata.shape)
sc.pp.highly_variable_genes(adata, n_top_genes=5000)
adata = adata[:, adata.var['highly_variable']]
print('Shape after: ', adata.shape)

Shape before:  (8811, 24929)
Shape after:  (8811, 5000)


Next we add the required TCR information as scirpy formatted covariates in the obs matrix:

In [15]:
df_tcr = pd.read_csv(f'{path_tcr}.tsv', sep='\t')
df_tcr['barcode'] = df_tcr.pop('CellID') # change cell IDs column name to "barcode"
df_tcr = df_tcr[df_tcr['study_id'].isin(selected_patients)] # keep only selected patients
df_tcr.to_csv(f'{path_tcr}.csv')

c:\Users\Jan\.conda\envs\mvtcr_preprocheck\lib\site-packages\IPython\core\interactiveshell.py:3266: DtypeWarning: Columns (38,39,40) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [16]:
adata_tcr = ir.io.read_10x_vdj(f'{path_tcr}.csv') # load with scirpy
ir.pp.merge_with_ir(adata, adata_tcr)
del adata_tcr

c:\Users\Jan\.conda\envs\mvtcr_preprocheck\lib\site-packages\scirpy\io\_convert_anndata.py:81: FutureWarning: X.dtype being converted to np.float32 from float64. In the next version of anndata (0.9) conversion will not be automatic. Pass dtype explicitly to avoid this warning. Pass `AnnData(X, dtype=X.dtype, ...)` to get the future behavour.
  adata = AnnData(obs=ir_df, X=np.empty([ir_df.shape[0], 0]))


mvTCR requires paired data between TCR and GEX. Therefore, we remove all samples without a TRA or TRB CDR3 region.

In [17]:
print(len(adata))
adata = adata[~(adata.obs['IR_VDJ_1_junction_aa'].isna() | adata.obs['IR_VJ_1_junction_aa'].isna())].copy()
print(len(adata))

8811
4227


## mvTCR preprocessing

In [18]:
'''
#This is only needed if you have not installed mvTCR in your conda environment and want to import the functions locally.
import sys
sys.path.append('..')
'''

In [19]:
from tcr_embedding.utils_preprocessing import Preprocessing

## All-in-one Pipeline

After we have a fitting dataset containing scirpy-encoded TCR information and expression data we can use mvTCR's preprocessing methods to further bring our data into shape.
The preprocessing pipeline is the fast way to do that your data. 

This features (in order):

- Checks for:
    - Normalization & log transformation checks (experimental)
    - "Reasonable" number of highly variable genes check (500 < n < 5000)
    - Scirpy VDJ gene usage information check
- Encoding of clonotypes
- Encoding of TCR
- One-Hot encoding of conditional variables
- Group-shuffle-splits (into train & validation datasets)

The required parameters and expected outputs of each step are explained in detail in the piece by piece preprocessing section below.

In [20]:
Preprocessing.preprocessing_pipeline(adata, 
                                     clonotype_key_added='clonotype', 
                                     column_cdr3a='IR_VJ_1_junction_aa', 
                                     column_cdr3b='IR_VDJ_1_junction_aa',
                                     cond_vars=['patient_id'],
                                     group_col='clonotype', 
                                     val_split=0.2)

100%|██████████| 4049/4049 [00:04<00:00, 847.41it/s]


In [21]:
adata.obs.set.value_counts()

train    3384
val       843
Name: set, dtype: int64

# Piece by Piece Preprocessing

All the features inside the pipeline can be executed seperately as well, to perform a step-by-setp preprocessing or only specific methods.

Make sure to freshly load the data if you have used the pipeline.

### Checking if adata is in a mvTCR compatible shape

In [22]:
Preprocessing.check_if_valid_adata(adata)

True

### Encoding clonotypes with Scirpy

For training the shared embedding, we advise oversampling rare clonotypes. This avoids the model overfitting to few selected TCR sequences from highly expanded clonotypes. Therefore, we need to add a clonotype label to adata.obs. Here, we define a unique clonotype via Scirpy as having exactly the same CDR3 sequence in TRA and TRB chains.

In [23]:
Preprocessing.encode_clonotypes(adata, key_added='clonotype')

adata.obs.clonotype.value_counts()

100%|██████████| 4049/4049 [00:03<00:00, 1202.07it/s]


2251    32
2207    25
2527     8
326      7
3277     7
        ..
1898     1
185      1
3797     1
2199     1
2421     1
Name: clonotype, Length: 4049, dtype: int64

### Adding TCR encoding

Next, we encode the TCR sequence numerically to adata.obsm. Here, we need to provide the name of the column storing the CDR3a and CDR3b. Additionally, we need to specificy the padding paremter (which if set to None uses the maximal CDR3 sequence length as default). If you plan to add new data in the future via a pretrained model, you might want to add some safety margin.

In [24]:
Preprocessing.encode_tcr(adata, column_cdr3a='IR_VJ_1_junction_aa', column_cdr3b='IR_VDJ_1_junction_aa', alpha_label_col='alpha_seq', alpha_length_col='alpha_len', beta_label_col='beta_seq', beta_length_col='beta_len', pad=None)

In [25]:
adata.obsm['beta_seq']

array([[ 2,  1, 16, ...,  0,  0,  0],
       [ 2, 16,  1, ...,  0,  0,  0],
       [ 2,  1, 17, ...,  0,  0,  0],
       ...,
       [ 2,  1, 16, ...,  0,  0,  0],
       [ 2,  1, 16, ...,  0,  0,  0],
       [ 2,  1, 16, ...,  0,  0,  0]])

### Adding conditional variables

Conditioning your model partially removes the effect from a specified condition. We can add conditional variables for e.g. donor, to avoid batch effects over multiple samples.

In [26]:
Preprocessing.encode_conditional_var(adata, column_id='patient_id')

In [27]:
adata.obsm['patient_id']

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

### Creating training and validation splits

The splitting improves the data spliting into training and validation sets by two properties:
- Stratified splitting: balance a label of interest (normally a variable to be predicted, e.g. antigen specificity) so the label distribution is roughly the same in both sets.
- Avoid training data leakage into validation: used for clonotypes, to ensure that each clonotype is observed only during training or validation.

In [28]:
train, val = Preprocessing.stratified_group_shuffle_split(adata.obs, stratify_col='full_clustering', group_col='clonotype', val_split=0.2, random_seed=42)

adata.obs['set'] = 'train'
adata.obs.loc[val.index, 'set'] = 'val'

100%|██████████| 23/23 [00:00<00:00, 106.85it/s]


In [29]:
adata.obs.set.value_counts()

train    3357
val       870
Name: set, dtype: int64

Alternatively group splitting is available by itself with:

In [30]:
gtrain, gval = Preprocessing.group_shuffle_split(adata, group_col='clonotype', val_split=0.2, random_seed=42)

In [31]:
adata.obs['set'] = 'train'
adata.obs.loc[gval.obs.index, 'set'] = 'val'

In [32]:
adata.obs.set.value_counts()

train    3384
val       843
Name: set, dtype: int64

### Finish. You are all set and done to use mvTCR! Save your data!

In [18]:
path_out = '../data/preprocessed/haniffa_test.h5ad'
adata.write_h5ad(path_out, compression='gzip')